name:                initiative
version:             0.1.0.0
github:              "githubuser/initiative"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/initiative#readme>

dependencies:
- base >= 4.7 && < 5
- text >= 1.2 && < 1.3
- brick >= 0.52 && < 0.53
- vty >= 5.28 && < 6.0
- microlens-platform >= 0.4 && < 0.5
- containers >= 0.6 && < 0.7
- mtl >= 2.2 && < 3.0
- yaml >= 0.11 && < 0.12
- aeson == 1.4.*
- random == 1.1.*
- parsec == 3.1.*
- split == 0.2.*

library:
  source-dirs: src

executables:
  initiative-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - initiative

tests:
  initiative-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - initiative
